print("Name          : Pavan Kumar")
print("Address       : Nellore")
print("D.O.B         : 25-10-2003")
print("Qualification : BTech")
print("Gender        : Male")
print("Email         : kpavan36668@gmail.com")
print("State         : Andhra Pradesh")
print("Citizenship   : Indian")
print("Father-Name   : Munisekhar")
print("Mother-Name   : Aruna")